### ISSUE TITLE
Segfault possibly related to OSC on startup

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#125]
On ubuntu quite frequently the programs fails and segfaults when started. Restarting it a few times usually solves the problem. Here is a backtrace that shows where the problem possibly originates:

```
(gdb) bt
#0  0x00007ffff715473b in lo_server_get_socket_fd (s=0x12c6cd0) at server.c:2033
#1  0x000000000045bb32 in OscReceiver::listen (this=0x152ec88) at OscReceiver.cpp:38
#2  0x000000000045855d in OscInterface::start (this=0x152ec80) at OscInterface.cpp:121
#3  0x0000000000435aa3 in MainWindow::startOscReceiver (this=0xdac400) at MainWindow.cpp:2430
#4  0x0000000000422b52 in MainWindow::MainWindow (this=0xdac400) at MainWindow.cpp:68
#5  0x0000000000434bb8 in MainWindow::instance () at MainWindow.cpp:2227
#6  0x000000000046ed22 in main (argc=1, argv=0x7fffffffdda8) at main.cpp:119
```

**Comment by loshermanos** [comment]
soft super cool pour l osc : http://i-score.org

Date: Mon, 13 Jul 2015 11:35:56 -0700

**Comment by sofian** [comment]
This seems linked to a dangling wrong OSC port in the settings. Run ./mapmap -R to reset the settings.

**Comment by sofian** [comment]
We still need to fix it though...

**Comment by sofian** [comment]
This bug seems to have been fixed.
