### ISSUE TITLE
QtMultimedia prototype

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#299]
The most recent version of QtMultimedia seems to finally be able to do what we need: get access to the raw data. It is becoming a viable alternative to GStreamer (which has many problems).

We need to make a test first. The easiest would probably be to implement a subclass of VideoImpl (see for example VideoV4l2SrcImpl).

**Comment by aalex** [comment]
If using Qt from the APT sources, it should be fine. However:

QTMultimedia from Qt 5.7 installer is broken on Ubuntu 16.10. https://bugreports.qt.io/browse/QTBUG-56640 - since Qt 5.7 relies on GStreamer 0.10, which has been removed.

Qt 5.8 (from installer) relies on GStreamer 1.0. It should be ok. (and provides the new QML Qt Quick Controls 2 - the version 1 is deprecated)

**Comment by skankerror** [comment]
Ok.

The weird thing is that I use mapmap on 2 laptops, both with qt5.7, and 
the other one worked fine. I'm not on ubuntu, I'm on manjaro (based on 
archlinux). Anyway I upgraded to qt5.8.

Here's another problem : I try to use osc ton control mapmap. 
/mapmap/play-pause-rewind work fine, but I get a segfault since I send 
other messages. For example : "sendOSC -h localhost 12345 
/mapmap/mapping/opacity ,if 1 0.5" :

Thread 1 "mapmap" received signal SIGABRT, Aborted.
0x00007ffff36cd04f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff36cd04f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff36ce47a in abort () at /usr/lib/libc.so.6
#2  0x0000000000434ca9 in mmp::ConsoleWindow::printMessage(QtMsgType, 
QMessageLogContext const&, QString const&) (this=0xddf8c0, 
type=QtFatalMsg, context=..., msg=...) at ConsoleWindow.cpp:127
#3  0x000000000049ecbb in logMessageHandler(QtMsgType, 
QMessageLogContext const&, QString const&) (type=QtFatalMsg, 
context=..., msg=...) at main.cpp:73
#4  0x00007ffff47fc0f8 in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff47fd996 in QMessageLogger::fatal(char const*, ...) const 
() at /usr/lib/libQt5Core.so.5
#6  0x00007ffff47f9261 in  () at /usr/lib/libQt5Core.so.5
#7  0x000000000047a9d9 in QList<QVariant>::at(int) const 
(this=0x7fffffffd230, i=2) at /usr/include/qt/QtCore/qlist.h:537
#8  0x0000000000479870 in 
mmp::OscInterface::applyOscCommand(mmp::MainWindow&, QList<QVariant>&) 
(this=0xfb1df0, main_window=..., command=...) at OscInterface.cpp:248
#9  0x0000000000478a50 in 
mmp::OscInterface::consume_commands(mmp::MainWindow&) (this=0xfb1df0, 
main_window=...)
     at OscInterface.cpp:106
#10 0x0000000000452e6a in mmp::MainWindow::pollOscInterface() 
(this=0xddec40) at MainWindow.cpp:3258
#11 0x0000000000564a71 in mmp::MainWindow::qt_static_metacall(QObject*, 
QMetaObject::Call, int, void**) (_o=0xddec40, 
_c=QMetaObject::InvokeMetaMethod, _id=38, _a=0x7fffffffd3f0) at 
moc_MainWindow.cpp:409
#12 0x00007ffff4a0b849 in QMetaObject::activate(QObject*, int, int, 
void**) () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff4a180f8 in QTimer::timerEvent(QTimerEvent*) () at 
/usr/lib/libQt5Core.so.5
#14 0x00007ffff4a0c76b in QObject::event(QEvent*) () at 
/usr/lib/libQt5Core.so.5
#15 0x00007ffff5fefa2c in QApplicationPrivate::notify_helper(QObject*, 
QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff5ff71b1 in QApplication::notify(QObject*, QEvent*) () at 
/usr/lib/libQt5Widgets.so.5
#17 0x00000000004387c7 in mmp::MainApplication::notify(QObject*, 
QEvent*) (this=0x7fffffffdc70, receiver=0xf4f780, event=0x7fffffffd840) 
at MainApplication.cpp:61
#18 0x00007ffff49e0ad8 in QCoreApplication::notifyInternal2(QObject*, 
QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff4a3207e in QTimerInfoList::activateTimers() () at 
/usr/lib/libQt5Core.so.5
#20 0x00007ffff4a32859 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007ffff6ee6587 in g_main_context_dispatch () at 
/usr/lib/libglib-2.0.so.0
#22 0x00007ffff6ee67f0 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff6ee689c in g_main_context_iteration () at 
/usr/lib/libglib-2.0.so.0
#24 0x00007ffff4a332df in 
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 
() at /usr/lib/libQt5Core.so.5
#25 0x00007ffff49df04a in 
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at 
/usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffff49e76e4 in QCoreApplication::exec() () at 
/usr/lib/libQt5Core.so.5
#27 0x00000000004a01d6 in main(int, char**) (argc=1, 
argv=0x7fffffffe338) at main.cpp:256

**Comment by sofian** [comment]
@skankerror Could you open a new issue for this? So that we do not get confused. Thanks.

**Comment by aalex** [comment]
@skankerror MapMap is not yet using QtMultimedia, so it doesn't make any difference which version of Qt you use. We use GStreamer 1.0. 

We are discussing a future potential port to QtMultimedia, since it's not quite obvious to use GStreamer on macOS. 

@sofian Another alternative would be to simply improve our packaging for macOS. We need to include the GStreamer.framework and the plugins we use in our .app.

**Comment by sofian** [comment]
Yes but we're still having issues with GStreamer (we're not using it the proper way) which results in videos not showing (eg. #321). I also think we might be having issues with memory leaks (remember we had a user who was reporting MapMap crashing after 10-15 minutes). So using QtMultimedia would likely make the whole process much cleaner and safe.

**Comment by aalex** [comment]
Might make #326 obsolete

**Comment by sofian** [comment]
The most simple and straightforward approach seems to be using QVideoProbe:
http://doc.qt.io/qt-5/qvideoprobe.html

(Go to section "Detailed example" there is an example of exactly what we are looking for. There is the equivalent for audio: http://doc.qt.io/qt-5/qaudioprobe.html)

This post says that QVideoProbe and QAudioProbe do not work in certain contexts (?) and shows another way to grab frames:
https://stackoverflow.com/questions/37724602/how-to-save-a-frame-using-qmediaplayer

**Comment by sofian** [comment]
I have done some tests with QtMultimedia on Ubuntu 16.04. Tried to run simple examples such as this one:
https://doc.qt.io/qt-5/qtmultimedia-multimediawidgets-camera-example.html

I was not able to do so. None of the examples I tried worked. I might be missing some plugins. But let's say that as a first test I am not very much impressed. Maybe the framework is not ready yet...

**Comment by sofian** [comment]
Gave another chance to QtMultimedia (on Ubuntu 17.10). This time I tried implementing frame grabbing on QMediaPlayer (you can view my work in the feature/qtmultimedia branch).

Implementation was easy. However, there's a nasty glitch when trying to "loop" the video: a black frame appears for a fraction of second (one frame presumably) towards the end. I tried many different ways to fix it and did not succeed.

I am starting to think that this might be a dead-end and that perhaps we should rather focus on refactoring / testing our GStreamer code.

**Comment by baydam** [comment]
Hey Sofian did you already try to let QMediaplaylist handle the looping as I do in this commit 43d0b4468a98b6cb4d20b1adc3e64deb9a09cd26.
It's work but still have a little lags. We can keep trying to make it work rather than continue to use Gstreamer

**Comment by sofian** [comment]
Yes I did try the media playlist with the "loop" option.
If you can find a way to avoid the "lag" then it changes everything of course. But I would not know where to start. If we cannot find the solution we should ask some QtMultimedia experts online on a forum or IRC.

**Comment by aalex** [comment]
Not an option right now, because there is a black frame each time the video loops. 

It uses the codec installed on the system. If there is no codec installed, it doesn't work.

It also lags.

**Comment by aalex** [comment]
Qt 6 offers a big refactor of Qt Multimedia: https://www.qt.io/blog/qt-multimedia-in-qt-6
