### ISSUE TITLE
Paint add/remove in undo/redo does not work when mappings are attached to paint

### ISSUE THREAD

**Issue by maxdee** [mapmapteam/mapmap#315]
Initially reported as: Crash when deleting last paint.
See below.

This points to a rather challenging issue wrt way paint add/remove is handled which might require a complete refactor of the way Command works (not sure yet).

Command should keep track of mappings attached to a paint.

**Comment by sofian** [comment]
Unable to reproduce: can you send a sequence of steps that produce the problem?
Also, if you could run with gdb and send a backtrace that would be great.

**Comment by maxdee** [comment]
- load a paint
- add a mapping
- select paint
- press delete
-- mapping gets deleted
- press delete again
-- crash

```
Starting program: /home/mxd/mapmap/fresh_mapmap/mapmap/mapmap 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7ca8700 (LWP 903)]
Listening on port 12345
[New Thread 0x7fffd8699700 (LWP 911)]
[New Thread 0x7fffd72ba700 (LWP 913)]
[Thread 0x7fffd72ba700 (LWP 913) exited]
[New Thread 0x7fffd72ba700 (LWP 918)]
[New Thread 0x7fffd5713700 (LWP 919)]
[New Thread 0x7fffd4afb700 (LWP 921)]
[New Thread 0x7fffc7dc3700 (LWP 922)]
[New Thread 0x7fffbf222700 (LWP 924)]
[New Thread 0x7fffbea21700 (LWP 925)]
[New Thread 0x7fffbe220700 (LWP 931)]
[New Thread 0x7fffbda1f700 (LWP 932)]
[New Thread 0x7fffbd21e700 (LWP 935)]
[New Thread 0x7fffbca1d700 (LWP 939)]
[Thread 0x7fffbf222700 (LWP 924) exited]
[Thread 0x7fffbea21700 (LWP 925) exited]
[Thread 0x7fffbe220700 (LWP 931) exited]
[Thread 0x7fffbda1f700 (LWP 932) exited]
[New Thread 0x7fffbda1f700 (LWP 942)]
[New Thread 0x7fffbe220700 (LWP 943)]
[New Thread 0x7fffbea21700 (LWP 945)]
[New Thread 0x7fffbf222700 (LWP 946)]
[New Thread 0x7fffa79e8700 (LWP 947)]
[New Thread 0x7fffa6fcb700 (LWP 948)]

Program received signal SIGABRT, Aborted.
0x00007ffff378b067 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff378b067 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff378c448 in __GI_abort () at abort.c:89
#2  0x000000000042aec9 in mmp::ConsoleWindow::printMessage (this=0xd1b040, 
    type=QtFatalMsg, context=..., msg=...) at ConsoleWindow.cpp:127
#3  0x0000000000493291 in logMessageHandler (type=QtFatalMsg, context=..., 
    msg=...) at main.cpp:73
#4  0x00007ffff4863587 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff48654d3 in QMessageLogger::fatal(char const*, ...) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff48602c7 in qt_assert_x(char const*, char const*, char const*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x000000000045bd75 in QList<mmp::MappingListModel::MappingItem>::at (
    this=0xfec9a0, i=0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:479
#8  0x000000000045b9ec in mmp::MappingListModel::getItemId (this=0xfec990, 
    index=...) at MappingListModel.cpp:264
#9  0x0000000000448697 in mmp::MainWindow::currentMappingItemId (this=0xd1a120)
    at MainWindow.cpp:3133
#10 0x00000000004336b1 in mmp::MainWindow::deleteMappingItem (this=0xd1a120)
    at MainWindow.cpp:794
#11 0x000000000055434a in mmp::MainWindow::qt_static_metacall (_o=0xd1a120, 
    _c=QMetaObject::InvokeMetaMethod, _id=16, _a=0x7fffffffd780)

```
